import React from "react";
import {
  FaLightbulb,
  FaClock,
  FaHashtag,
  FaArrowTrendUp,
} from "react-icons/fa6";

const defaultRecommendations = [
  {
    title: "Improve Engagement",
    description: "Use a stronger hook within the first 3 seconds of your content.",
    icon: <FaArrowTrendUp />,
    priority: "High",
  },
  {
    title: "Best Posting Time",
    description: "Post between 7 PM and 9 PM for maximum audience reach.",
    icon: <FaClock />,
    priority: "Medium",
  },
  {
    title: "Trending Hashtags",
    description: "#CreatorIQ #AI #Tech #ContentCreator",
    icon: <FaHashtag />,
    priority: "Low",
  },
];

const RecommendationCard = ({ suggestions = [] }) => {
  const displayRecommendations = suggestions.length > 0
    ? suggestions.map((text, idx) => {
        const icons = [<FaArrowTrendUp />, <FaClock />, <FaHashtag />, <FaLightbulb />];
        const priorities = ["High", "Medium", "Low"];
        const titles = ["Content Strategy", "Posting & Schedule", "Optimization Technique", "Engagement Focus"];
        return {
          title: titles[idx % titles.length],
          description: text,
          icon: icons[idx % icons.length],
          priority: priorities[idx % priorities.length],
        };
      })
    : defaultRecommendations;

  return (
    <div className="bg-white rounded-2xl shadow-md border border-gray-100 p-8">

      {/* Header */}

      <div className="flex items-center gap-4 mb-8">

        <div className="w-14 h-14 rounded-2xl bg-blue-100 flex items-center justify-center text-blue-600 text-2xl">
          <FaLightbulb />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-gray-800">
            AI Recommendations
          </h2>

          <p className="text-gray-500">
            Personalized suggestions generated by AI
          </p>
        </div>

      </div>

      {/* Cards */}

      <div className="space-y-5">

        {displayRecommendations.map((item, index) => (

          <div
            key={index}
            className="border border-gray-200 rounded-xl p-5 hover:shadow-md transition-all duration-300"
          >

            <div className="flex justify-between items-start">

              <div className="flex gap-4">

                <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center text-xl">
                  {item.icon}
                </div>

                <div>

                  <h3 className="font-semibold text-lg text-gray-800">
                    {item.title}
                  </h3>

                  <p className="text-gray-500 mt-1">
                    {item.description}
                  </p>

                </div>

              </div>

              <span
                className={`px-3 py-1 rounded-full text-sm font-medium ${
                  item.priority === "High"
                    ? "bg-red-100 text-red-600"
                    : item.priority === "Medium"
                    ? "bg-yellow-100 text-yellow-600"
                    : "bg-green-100 text-green-600"
                }`}
              >
                {item.priority}
              </span>

            </div>

          </div>

        ))}

      </div>

    </div>
  );
};

export default RecommendationCard;